export const SET_TIMEOUT_ID_COMPETITIONS = 'SET_TIMEOUT_ID_COMPETITIONS';
export const CLEAR_TIMEOUT_ID_COMPETITIONS = 'CLEAR_TIMEOUT_ID_COMPETITIONS';
export const TOGGLE_IS_LOADING_COMPETITIONS = 'TOGGLE_IS_LOADING_COMPETITIONS';
export const TOGGLE_ERROR_COMPETITIONS = 'TOGGLE_ERROR_COMPETITIONS';
export const RESP_COMPETITIONS = 'RESP_COMPETITIONS';
