export const SET_TIMEOUT_ID_EVENTTYPES = 'SET_TIMEOUT_ID_EVENTTYPES';
export const CLEAR_TIMEOUT_ID_EVENTTYPES = 'CLEAR_TIMEOUT_ID_EVENTTYPES';
export const TOGGLE_IS_LOADING_EVENTTYPES = 'TOGGLE_IS_LOADING_EVENTTYPES';
export const TOGGLE_ERROR_EVENTTYPES = 'TOGGLE_ERROR_EVENTTYPES';
export const RESP_EVENTTYPES = 'RESP_EVENTTYPES';
